### ISSUE TITLE
SEGMENTATION FAULTTTTTTT

### ISSUE THREAD

**Issue by echaussidon** [RemyChatel/HyperplanningParser#1]
Bonjour, 

je ne comprends pas quand je run `gcc -std=c99 -o master hyper planning.py` le code ne veut pas compiler :flushed:

ps : c'est vraiment rigolo comme petit programme, bravo je te mets un pouce sur Linkedin pour tes competences en programmation :heart_eyes:

**Comment by RemyChatel** [comment]
Ahaha !
Il doit y avoir un problème sur le pointeur d'adresse de WALI-M ... ;)
